Dotson contrib
arfc/2019-09-05-group pull request #11
Opened 2019-09-03 21:50 UTC by samgdotson

Adds images and slides for `dotson.tex`. Both annsa and reactor control project are included under the title of "Machine Learning Applications in Nuclear Engineering."

2019-09-04 18:39 UTC, smpark7 commented
Hey Sam!

You don't need to include a preamble in dotson.tex because it is already included in the arfc-pres.tex file. The arfc-pres.tex file imports your dotson.tex so that everyone's slides are imported into the one presentation pdf file (arfc-pres.pdf). 

Also, a more descriptive figure caption would be helpful for the ANNSA CNN figure.

2019-09-04 18:52 UTC, samgdotson commented
> You don't need to include a preamble in dotson.tex because it is already included in the arfc-pres.tex file. The arfc-pres.tex file imports your dotson.tex so that everyone's slides are imported into the one presentation pdf file (arfc-pres.pdf).

I left the `\graphicspath{}` because `make` was throwing a fit when I commented it out.

2019-09-05 17:29 UTC, smpark7 commented on dotson.tex
> +\graphicspath{{./images/}}
```suggestion
```

2019-09-05 17:35 UTC, smpark7 requested changes

2019-09-05 17:35 UTC, smpark7 commented on dotson.tex
> +	\section{ANNSA}
```suggestion
```
This probably falls under the software section

2019-09-05 17:35 UTC, smpark7 commented on dotson.tex
> +	\section{CAIRO}
```suggestion
```
This falls under software section too?

2019-09-05 19:19 UTC, merged

2019-09-09 20:23 UTC, samgdotson commented
closes issue #11